### ISSUE TITLE
Equivalent of Laravel's queue:listen task

### ISSUE THREAD

**Issue by markguinn** [studiobonito/silverstripe-queue#1]
Is there an equivalent of Laravels queue:listen task? I see you can run the processing task with daemon=1 but it appears to terminate once all tasks in the queue have been completed. Do you recommend just running the processing task via cron? Do you have plans to implement a listener type task as well?

**Comment by nedmas** [comment]
As you've correctly discovered the daemon=1 option is designed to continually listen to the queue and execute jobs. And yes our intention has always been to run the processing task via cron.

If the daemon option isn't working then that needs to be fixed (PR always welcome). And as far as an equivalent for queue:listen I don't see the need for a separate task, unless there's something specific that can't be achieved using the daemon option (when it's working).

**Comment by markguinn** [comment]
I'm working on a project using this module right now so if time allows I'll have a look at fixing the daemon mode. Can't make any promises but hopefully that will work out. Thanks for making this module! It seems to work really well out of the box with just the database driver.

**Comment by nedmas** [comment]
Thanks, that would be fantastic! I'm going to close this issue as the queue:listen task is resolved, and I'll open another one for the broken daemon option.
